import { storage } from "./storage";
import { type InsertItem, type InsertLook, type InsertStory, type InsertCollection } from "@shared/schema";

export async function seedData() {
  // Seed Items
  const items: InsertItem[] = [
    {
      sku: "SKU001",
      name: "Premium Leather Jacket",
      images: ["/generated_images/Product_leather_jacket_a13fb76c.png"],
      price: 199,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Black",
      material: "Genuine Leather",
      sustainTags: ["Eco-friendly tanning", "Recycled lining"],
      stock: 12,
      description: "Classic leather jacket with a modern twist.",
      category: "outerwear",
      occasion: ["casual", "party"],
      colorFamily: "black",
    },
    {
      sku: "SKU002",
      name: "White Turtleneck",
      images: ["/generated_images/Product_basic_tee_7cb6d64a.png"],
      price: 29,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "White",
      material: "Organic Cotton",
      sustainTags: ["100% Organic Cotton"],
      stock: 45,
      description: "Essential white turtleneck for layering.",
      category: "tops",
      occasion: ["casual", "business"],
      colorFamily: "white",
    },
    {
      sku: "SKU003",
      name: "Wool Scarf",
      images: ["/generated_images/Beige_wool_scarf_product_bd9462cf.png"],
      price: 35,
      sizes: ["One Size"],
      color: "Beige",
      material: "Merino Wool",
      sustainTags: ["Responsible Wool"],
      stock: 28,
      description: "Soft merino wool scarf for cold days.",
      category: "accessories",
      occasion: ["casual", "formal"],
      colorFamily: "beige",
    },
    {
      sku: "SKU004",
      name: "Knit Sweater",
      images: ["/generated_images/Product_knit_sweater_77d57eeb.png"],
      price: 49,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Beige",
      material: "Cotton Blend",
      sustainTags: [],
      stock: 30,
      description: "Cozy knit sweater perfect for weekends.",
      category: "tops",
      occasion: ["casual"],
      colorFamily: "beige",
    },
    {
      sku: "SKU005",
      name: "Denim Jeans",
      images: ["/generated_images/Product_denim_jeans_ce699130.png"],
      price: 59,
      sizes: ["26", "28", "30", "32", "34"],
      color: "Blue",
      material: "Denim",
      sustainTags: ["Water-saving production"],
      stock: 50,
      description: "Classic blue denim with modern fit.",
      category: "bottoms",
      occasion: ["casual"],
      colorFamily: "blue",
    },
    {
      sku: "SKU006",
      name: "Floral Midi Dress",
      images: ["/generated_images/Floral_midi_dress_product_bd176bd1.png"],
      price: 79,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Multicolor",
      material: "Recycled Polyester",
      sustainTags: ["Made from recycled materials"],
      stock: 22,
      description: "Elegant floral dress perfect for any occasion.",
      category: "dresses",
      occasion: ["casual", "party"],
      colorFamily: "multicolor",
    },
    {
      sku: "SKU007",
      name: "Tailored Blazer",
      images: ["/generated_images/Navy_tailored_blazer_product_b2b39374.png"],
      price: 129,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Navy",
      material: "Wool Blend",
      sustainTags: ["Responsible Wool"],
      stock: 18,
      description: "Professional blazer with modern fit.",
      category: "outerwear",
      occasion: ["business", "formal"],
      colorFamily: "blue",
    },
    {
      sku: "SKU008",
      name: "Silk Blouse",
      images: ["/generated_images/Cream_silk_blouse_product_73677d24.png"],
      price: 69,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Cream",
      material: "Silk",
      sustainTags: [],
      stock: 25,
      description: "Luxurious silk blouse for elegant looks.",
      category: "tops",
      occasion: ["business", "formal", "party"],
      colorFamily: "beige",
    },
    {
      sku: "SKU009",
      name: "Wide-Leg Trousers",
      images: ["/generated_images/Black_wide-leg_trousers_product_4a36eac6.png"],
      price: 69,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Black",
      material: "Cotton Blend",
      sustainTags: ["Water-saving production"],
      stock: 30,
      description: "Sophisticated wide-leg trousers.",
      category: "bottoms",
      occasion: ["business", "formal"],
      colorFamily: "black",
    },
    {
      sku: "SKU010",
      name: "Striped Cotton T-Shirt",
      images: ["/generated_images/Striped_cotton_t-shirt_product_1da93eda.png"],
      price: 19,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      color: "Blue/White",
      material: "100% Cotton",
      sustainTags: ["Organic Cotton"],
      stock: 60,
      description: "Classic striped tee for everyday wear.",
      category: "tops",
      occasion: ["casual"],
      colorFamily: "blue",
    },
    {
      sku: "SKU011",
      name: "Black Ankle Boots",
      images: ["/generated_images/Black_ankle_boots_product_795461dc.png"],
      price: 89,
      sizes: ["36", "37", "38", "39", "40", "41"],
      color: "Black",
      material: "Faux Leather",
      sustainTags: [],
      stock: 25,
      description: "Versatile ankle boots for any season.",
      category: "shoes",
      occasion: ["casual", "business"],
      colorFamily: "black",
    },
    {
      sku: "SKU012",
      name: "Cashmere Cardigan",
      images: ["/generated_images/Gray_cashmere_cardigan_product_09938aa5.png"],
      price: 149,
      sizes: ["S", "M", "L", "XL"],
      color: "Gray",
      material: "100% Cashmere",
      sustainTags: ["Responsible Sourcing"],
      stock: 15,
      description: "Luxurious cashmere cardigan.",
      category: "tops",
      occasion: ["casual", "business"],
      colorFamily: "gray",
    },
    {
      sku: "SKU013",
      name: "Pencil Skirt",
      images: ["/generated_images/Black_pencil_skirt_product_ee3c025a.png"],
      price: 45,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Black",
      material: "Ponte Knit",
      sustainTags: [],
      stock: 35,
      description: "Classic pencil skirt for office wear.",
      category: "bottoms",
      occasion: ["business", "formal"],
      colorFamily: "black",
    },
    {
      sku: "SKU014",
      name: "Evening Gown",
      images: ["/generated_images/Burgundy_evening_gown_product_86ae3e02.png"],
      price: 199,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Burgundy",
      material: "Silk Blend",
      sustainTags: [],
      stock: 8,
      description: "Elegant floor-length evening gown.",
      category: "dresses",
      occasion: ["formal", "party"],
      colorFamily: "red",
    },
    {
      sku: "SKU015",
      name: "Trench Coat",
      images: ["/generated_images/Beige_trench_coat_product_b5afc5dd.png"],
      price: 179,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Beige",
      material: "Cotton Blend",
      sustainTags: ["Water-resistant"],
      stock: 20,
      description: "Classic trench coat for rainy days.",
      category: "outerwear",
      occasion: ["casual", "business"],
      colorFamily: "beige",
    },
    {
      sku: "SKU016",
      name: "Linen Shirt",
      images: ["/generated_images/White_linen_shirt_product_08743d80.png"],
      price: 49,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      color: "White",
      material: "100% Linen",
      sustainTags: ["Natural Fibers"],
      stock: 40,
      description: "Breathable linen shirt for summer.",
      category: "tops",
      occasion: ["casual", "formal"],
      colorFamily: "white",
    },
    {
      sku: "SKU017",
      name: "Chino Pants",
      images: ["/generated_images/Khaki_chino_pants_product_cc18eb4a.png"],
      price: 55,
      sizes: ["28", "30", "32", "34", "36", "38"],
      color: "Khaki",
      material: "Cotton Twill",
      sustainTags: [],
      stock: 45,
      description: "Versatile chino pants for smart casual looks.",
      category: "bottoms",
      occasion: ["casual", "business"],
      colorFamily: "beige",
    },
    {
      sku: "SKU018",
      name: "Cocktail Dress",
      images: ["/generated_images/Black_cocktail_dress_product_7cb071fb.png"],
      price: 119,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Black",
      material: "Polyester Blend",
      sustainTags: [],
      stock: 18,
      description: "Chic cocktail dress for evening events.",
      category: "dresses",
      occasion: ["party", "formal"],
      colorFamily: "black",
    },
    {
      sku: "SKU019",
      name: "Puffer Jacket",
      images: ["/generated_images/Navy_puffer_jacket_product_f51b9ecc.png"],
      price: 139,
      sizes: ["S", "M", "L", "XL", "XXL"],
      color: "Navy",
      material: "Recycled Nylon",
      sustainTags: ["Recycled Materials", "Animal-free"],
      stock: 32,
      description: "Warm puffer jacket with recycled filling.",
      category: "outerwear",
      occasion: ["casual", "sport"],
      colorFamily: "blue",
    },
    {
      sku: "SKU020",
      name: "V-Neck Sweater",
      images: ["/generated_images/Burgundy_v-neck_sweater_product_b34759d8.png"],
      price: 39,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Burgundy",
      material: "Acrylic Blend",
      sustainTags: [],
      stock: 38,
      description: "Classic V-neck sweater in rich burgundy.",
      category: "tops",
      occasion: ["casual", "business"],
      colorFamily: "red",
    },
    {
      sku: "SKU021",
      name: "Leather Belt",
      images: ["/generated_images/Brown_leather_belt_product_b186730d.png"],
      price: 29,
      sizes: ["S", "M", "L"],
      color: "Brown",
      material: "Genuine Leather",
      sustainTags: [],
      stock: 55,
      description: "Classic leather belt with brass buckle.",
      category: "accessories",
      occasion: ["casual", "business", "formal"],
      colorFamily: "brown",
    },
    {
      sku: "SKU022",
      name: "Sneakers",
      images: ["/generated_images/White_canvas_sneakers_product_cdf1144c.png"],
      price: 79,
      sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
      color: "White",
      material: "Canvas",
      sustainTags: ["Vegan"],
      stock: 48,
      description: "Classic white canvas sneakers.",
      category: "shoes",
      occasion: ["casual", "sport"],
      colorFamily: "white",
    },
    {
      sku: "SKU023",
      name: "Maxi Dress",
      images: ["/generated_images/Floral_maxi_dress_product_5af834b3.png"],
      price: 89,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Floral Print",
      material: "Rayon",
      sustainTags: [],
      stock: 24,
      description: "Flowing maxi dress with floral print.",
      category: "dresses",
      occasion: ["casual", "party"],
      colorFamily: "multicolor",
    },
    {
      sku: "SKU024",
      name: "Hooded Sweatshirt",
      images: ["/generated_images/Gray_hooded_sweatshirt_product_c0c608fe.png"],
      price: 45,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      color: "Gray",
      material: "Cotton Fleece",
      sustainTags: ["Organic Cotton"],
      stock: 52,
      description: "Comfortable hoodie for casual days.",
      category: "tops",
      occasion: ["casual", "sport"],
      colorFamily: "gray",
    },
    {
      sku: "SKU025",
      name: "Pleated Midi Skirt",
      images: ["/generated_images/Pink_pleated_skirt_product_0b9af31c.png"],
      price: 65,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Pink",
      material: "Polyester",
      sustainTags: [],
      stock: 28,
      description: "Feminine pleated midi skirt.",
      category: "bottoms",
      occasion: ["casual", "party"],
      colorFamily: "pink",
    },
    {
      sku: "SKU026",
      name: "Bomber Jacket",
      images: ["/generated_images/Green_bomber_jacket_product_57bccabc.png"],
      price: 99,
      sizes: ["S", "M", "L", "XL"],
      color: "Green",
      material: "Nylon",
      sustainTags: [],
      stock: 22,
      description: "Classic bomber jacket in olive green.",
      category: "outerwear",
      occasion: ["casual"],
      colorFamily: "green",
    },
    {
      sku: "SKU027",
      name: "Button-Down Shirt",
      images: ["/generated_images/Blue_oxford_shirt_product_1b1fb38e.png"],
      price: 39,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      color: "Blue",
      material: "Cotton",
      sustainTags: [],
      stock: 44,
      description: "Classic button-down oxford shirt.",
      category: "tops",
      occasion: ["business", "casual"],
      colorFamily: "blue",
    },
    {
      sku: "SKU028",
      name: "Yoga Pants",
      images: ["/generated_images/Black_yoga_pants_product_2efa2121.png"],
      price: 49,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Black",
      material: "Spandex Blend",
      sustainTags: [],
      stock: 60,
      description: "Stretchy yoga pants for workouts.",
      category: "bottoms",
      occasion: ["sport"],
      colorFamily: "black",
    },
    {
      sku: "SKU029",
      name: "Sunglasses",
      images: ["/generated_images/Black_aviator_sunglasses_product_e6831b5c.png"],
      price: 35,
      sizes: ["One Size"],
      color: "Black",
      material: "Acetate",
      sustainTags: [],
      stock: 70,
      description: "Classic aviator sunglasses.",
      category: "accessories",
      occasion: ["casual"],
      colorFamily: "black",
    },
    {
      sku: "SKU030",
      name: "Wrap Dress",
      images: ["/generated_images/Red_wrap_dress_product_a8109357.png"],
      price: 75,
      sizes: ["XS", "S", "M", "L", "XL"],
      color: "Red",
      material: "Jersey Knit",
      sustainTags: [],
      stock: 26,
      description: "Flattering wrap dress in vibrant red.",
      category: "dresses",
      occasion: ["casual", "business", "party"],
      colorFamily: "red",
    },
  ];

  for (const item of items) {
    await storage.createItem(item);
  }

  // Seed Looks
  const looks: InsertLook[] = [
    {
      title: "Autumn Layers",
      items: [
        { sku: "SKU001", name: "Premium Leather Jacket", price: 199 },
        { sku: "SKU002", name: "White Turtleneck", price: 29 },
        { sku: "SKU003", name: "Wool Scarf", price: 35 },
      ],
      heroImage: "/generated_images/Story_card_autumn_look_7a4bbbf6.png",
      tags: ["Sustainability", "Layering"],
      sustainBadges: ["Eco-friendly materials"],
      substitutes: [],
      availabilityState: "available"
    },
    {
      title: "Cozy Weekend",
      items: [
        { sku: "SKU004", name: "Knit Sweater", price: 49 },
        { sku: "SKU005", name: "Denim Jeans", price: 59 },
      ],
      heroImage: "/generated_images/Story_card_workwear_look_a3ea8ce1.png",
      tags: ["Casual", "Comfort"],
      sustainBadges: [],
      substitutes: [],
      availabilityState: "available"
    },
    {
      title: "Spring Garden",
      items: [
        { sku: "SKU006", name: "Floral Midi Dress", price: 79 },
      ],
      heroImage: "/generated_images/Story_card_summer_look_b5f6c911.png",
      tags: ["Floral", "Spring"],
      sustainBadges: ["Made from recycled materials"],
      substitutes: [],
      availabilityState: "available"
    },
    {
      title: "Office Chic",
      items: [
        { sku: "SKU007", name: "Tailored Blazer", price: 129 },
        { sku: "SKU008", name: "Silk Blouse", price: 69 },
        { sku: "SKU009", name: "Wide-Leg Trousers", price: 69 },
      ],
      heroImage: "/generated_images/Story_card_workwear_look_a3ea8ce1.png",
      tags: ["Professional", "Elegant"],
      sustainBadges: ["Responsible Wool"],
      substitutes: [],
      availabilityState: "available"
    },
  ];

  const lookIds: string[] = [];
  for (const look of looks) {
    const created = await storage.createLook(look);
    lookIds.push(created.id);
  }

  // Seed Stories
  const stories: InsertStory[] = [
    {
      title: "Autumn Essentials",
      narrativeMd: `As the leaves begin their chromatic transformation and the air takes on that unmistakable crispness, there's an inherent shift in our relationship with fashion. This season, we're celebrating the art of layering—not merely as a practical necessity, but as an opportunity for self-expression and sustainable style.

Our Autumn Essentials collection embodies this philosophy, bringing together pieces that transcend fleeting trends to become true wardrobe investments. At the heart of this narrative stands our Premium Leather Jacket, crafted from ethically sourced leather with eco-friendly tanning processes. It's more than outerwear; it's a statement of conscious luxury that improves with age, developing a unique patina that tells your story.

Beneath, the foundation of any autumn wardrobe: our White Turtleneck in 100% organic cotton. Its minimalist elegance provides the perfect canvas for layering, offering versatility that extends from weekend market runs to sophisticated evening gatherings. Pair it with our responsibly sourced Merino Wool Scarf, and you've created a trifecta of timeless style and environmental consciousness.

This collection represents more than clothing—it's an invitation to embrace the season with intention, choosing pieces that honor both craft and planet. Each item has been selected to complement the others, creating endless possibilities for personal expression while minimizing environmental impact.`,
      lookIds: [lookIds[0]],
      images: ["/generated_images/Story_card_autumn_look_7a4bbbf6.png", "/generated_images/Story_card_workwear_look_a3ea8ce1.png"],
      femaleImages: ["/generated_images/Story_card_autumn_look_7a4bbbf6.png"],
      maleImages: ["/generated_images/Male_autumn_essentials_trench_coat_2a809354.png"],
      mannequinImages: ["/generated_images/Mannequin_autumn_trench_coat_554a0aed.png"],
      tags: ["Sustainability", "Fall"],
      lookCount: 2
    },
    {
      title: "Summer Breeze",
      narrativeMd: `Summer dressing should feel effortless—a second skin that moves with you through sun-drenched days and balmy evenings. Our Summer Breeze collection captures this essence, offering pieces that prioritize both comfort and conscious design.

There's a particular freedom in summer style that we've channeled into this curated selection. The Knit Sweater in our signature beige becomes your companion for those cooler coastal evenings, while our water-conscious Denim Jeans provide the perfect foundation for endless summer adventures. These aren't just clothes; they're enablers of experience, designed to support your most authentic summer self.

We've reimagined casual wear through the lens of sustainability, proving that environmental responsibility and effortless style are not mutually exclusive. Each piece in this collection has been chosen for its ability to transition seamlessly from beach gatherings to sunset dinners, embodying the relaxed sophistication that defines the season.

This is summer dressing at its finest—uncomplicated, authentic, and aligned with your values. It's about creating space for life's moments while treading lightly on the earth.`,
      lookIds: [lookIds[1]],
      images: ["/generated_images/Story_card_summer_look_b5f6c911.png"],
      femaleImages: ["/generated_images/Story_card_summer_look_b5f6c911.png"],
      maleImages: ["/generated_images/Male_summer_casual_outfit_fae64d47.png"],
      mannequinImages: ["/generated_images/Mannequin_summer_casual_outfit_16a94576.png"],
      tags: ["Fresh", "Summer"],
      lookCount: 1
    },
    {
      title: "Spring Garden",
      narrativeMd: `Spring arrives not with fanfare but with whispers—the first bloom, the subtle shift in light, the gentle warming of the earth. Our Spring Garden collection embodies this delicate awakening, celebrating renewal through sustainable craftsmanship and botanical inspiration.

The Floral Midi Dress stands as the centerpiece of this narrative, crafted entirely from recycled polyester yet retaining all the fluid grace of traditional fabrics. Its vibrant botanical print captures the essence of a garden in full bloom, while its thoughtful construction speaks to our commitment to circular fashion. This is conscious design at its most elegant—proving that sustainability can be beautiful, feminine, and utterly covetable.

This season, we invite you to embrace a slower, more intentional approach to dressing. Each piece has been designed to transcend seasonal boundaries, becoming a cherished part of your wardrobe for years to come. The floral motifs aren't merely decorative—they're a celebration of nature's resilience and beauty, a reminder to honor the world that inspires us.

Spring Garden represents fashion's future: thoughtful, sustainable, and deeply connected to the natural world. It's an invitation to bloom alongside the season, expressing your most vibrant self while nurturing the planet.`,
      lookIds: [lookIds[2]],
      images: ["/generated_images/Story_card_summer_look_b5f6c911.png"],
      femaleImages: ["/generated_images/Story_card_summer_look_b5f6c911.png"],
      maleImages: ["/generated_images/Male_spring_garden_look_28619890.png"],
      mannequinImages: ["/generated_images/Mannequin_spring_floral_dress_9fcf178b.png"],
      tags: ["Floral", "Sustainable"],
      lookCount: 1
    },
    {
      title: "Workwear Edit",
      narrativeMd: `Modern professional dressing demands more than just polish—it requires pieces that empower, inspire confidence, and reflect your personal narrative while commanding respect in any room you enter. Our Workwear Edit collection redefines power dressing for the contemporary professional.

At its foundation lies the Tailored Blazer, constructed from responsibly sourced wool blend with a cut that flatters while allowing freedom of movement. This isn't your mother's boardroom attire; it's been reimagined for the woman who leads meetings, closes deals, and mentors the next generation—all before lunch. Paired with our luxurious Silk Blouse in cream, it creates a harmony of structure and softness that speaks to the multifaceted nature of modern professionalism.

The Wide-Leg Trousers complete this triumvirate, offering a sophisticated silhouette that bridges boardroom formality with creative sector cool. Crafted using water-saving production methods, they prove that professional excellence and environmental consciousness can coexist beautifully.

This collection celebrates the evolution of workwear, honoring tradition while pushing boundaries. These are investment pieces designed to support your ambitions, crafted with attention to detail that speaks to your own commitment to excellence. Because true professional power comes not from conformity, but from authentic self-expression grounded in quality and values.`,
      lookIds: [lookIds[3]],
      images: ["/generated_images/Story_card_workwear_look_a3ea8ce1.png"],
      femaleImages: ["/generated_images/Story_card_workwear_look_a3ea8ce1.png"],
      maleImages: ["/generated_images/Male_workwear_blazer_look_1bca3e0c.png"],
      mannequinImages: ["/generated_images/Mannequin_workwear_blazer_9fbfc675.png"],
      tags: ["Professional", "Tailored"],
      lookCount: 1
    },
  ];

  for (const story of stories) {
    await storage.createStory(story);
  }

  // Seed Collections
  const collections: InsertCollection[] = [
    {
      title: "Autumn Essentials",
      description: "Discover the perfect pieces for fall layering. From premium leather to cozy knits, this collection brings together timeless staples that transition seamlessly from crisp morning walks to evening gatherings.",
      editorialImages: [
        {
          url: "/generated_images/Story_card_autumn_look_7a4bbbf6.png",
          caption: "Autumn Layers",
          itemSkus: ["SKU001", "SKU002", "SKU003"],
        },
        {
          url: "/generated_images/Story_card_workwear_look_a3ea8ce1.png",
          caption: "Cozy Weekend",
          itemSkus: ["SKU004", "SKU005"],
        },
      ],
      itemSkus: ["SKU001", "SKU002", "SKU003", "SKU004", "SKU005"],
      tags: ["Sustainability", "Layering", "Fall"],
      season: "Fall/Winter 2025",
    },
    {
      title: "Spring Awakening",
      description: "Embrace the season of renewal with flowing silhouettes and vibrant florals. Each piece in this collection celebrates sustainable craftsmanship and effortless elegance.",
      editorialImages: [
        {
          url: "/generated_images/Story_card_summer_look_b5f6c911.png",
          caption: "Garden Party",
          itemSkus: ["SKU006"],
        },
      ],
      itemSkus: ["SKU006"],
      tags: ["Floral", "Sustainable", "Spring"],
      season: "Spring/Summer 2025",
    },
    {
      title: "Workwear Edit",
      description: "Professional pieces that command attention. This curated selection brings together tailored excellence and timeless sophistication for the modern professional.",
      editorialImages: [
        {
          url: "/generated_images/Story_card_workwear_look_a3ea8ce1.png",
          caption: "Office Chic",
          itemSkus: ["SKU007", "SKU008", "SKU009"],
        },
      ],
      itemSkus: ["SKU007", "SKU008", "SKU009"],
      tags: ["Professional", "Tailored", "Elegant"],
      season: "Year-Round",
    },
  ];

  for (const collection of collections) {
    await storage.createCollection(collection);
  }

  console.log('✅ Seed data loaded successfully');
}
